# Generated by Django 5.1.7 on 2025-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='roles',
            field=models.CharField(blank=True, choices=[('coach', 'Entraineur'), ('member', 'Membre'), ('president', 'Président'), ('treasurer', 'Trésorier'), ('vice-president', 'Vice-Président'), ('secretary', 'Secrétaire'), ('web-master', 'Web-master'), ('visitor', 'Visiteur'), ('testman', 'Testman')], default='visitor', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='weapon',
            field=models.CharField(blank=True, choices=[('epee', 'Épée'), ('fleuret', 'Fleuret'), ('sabre', 'Sabre')], max_length=10, null=True, verbose_name='weapon'),
        ),
    ]
