# Generated by Django 5.1.7 on 2025-04-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sports_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.sportscategory', verbose_name='Sports Category'),
        ),
        migrations.AddField(
            model_name='membershipfee',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='members.member'),
        ),
        migrations.AddField(
            model_name='membershipfee',
            name='sports_category',
            field=models.ForeignKey(blank=True, help_text='Catégorie associée à ce paiement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.sportscategory', verbose_name='Category'),
        ),
    ]
