# Generated by Django 5.1.7 on 2025-03-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='roles',
            field=models.CharField(blank=True, choices=[('president', 'Président'), ('vice-president', 'Vice-Président'), ('treasurer', 'Trésorier'), ('secretary', 'Secrétaire'), ('coach', "Maître d'armes"), ('member', 'Membre'), ('web-master', 'Web-master'), ('testman', 'Testman')], default='visitor', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente'), ('inactive', 'Inactif')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
