# Generated by Django 5.1.6 on 2025-02-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_staff',
        ),
    ]
