# Generated by Django 5.1.7 on 2025-04-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='handeness',
        ),
        migrations.AddField(
            model_name='member',
            name='handedness',
            field=models.CharField(blank=True, choices=[('right', 'Droitier'), ('left', 'Gaucher'), ('ambidextrous', 'Ambidextre')], max_length=15, null=True, verbose_name='Handedness'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Complement'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='weapon',
            field=models.CharField(blank=True, choices=[('epee', 'Épée'), ('fleuret', 'Fleuret'), ('sabre', 'Sabre')], max_length=10, null=True, verbose_name='Weapon'),
        ),
    ]
