# Generated by Django 5.1.7 on 2025-03-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_gender_alter_member_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipfee',
            name='sports_category',
            field=models.ForeignKey(blank=True, help_text='Catégorie associée à ce paiement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.sportscategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='sportscategory',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la cotisation pour cette catégorie', max_digits=6, null=True, verbose_name='Membership Fee (€)'),
        ),
    ]
