# Generated by Django 5.1.6 on 2025-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(default='Membres', related_name='members', to='members.role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, default='Escrimeur', related_name='members', to='members.tag'),
        ),
    ]
