# Generated by Django 5.1.7 on 2025-03-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_membershipfee_sports_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipfee',
            options={'ordering': ['member']},
        ),
        migrations.RemoveField(
            model_name='membershipfee',
            name='payment_date',
        ),
    ]
