# Generated by Django 5.1.7 on 2025-03-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_membershipfee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipfee',
            name='amount',
        ),
    ]
