# Generated by Django 5.1.7 on 2025-03-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_membershipfee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfee',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Valid Payment'),
        ),
    ]
