# Generated by Django 5.1.7 on 2025-05-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
