# Generated by Django 5.1.7 on 2025-03-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mapslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapslocation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
