# Generated by Django 5.1.7 on 2025-03-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la cotisation pour cette catégorie', max_digits=6, null=True, verbose_name='Membership Fee (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sports categories',
                'ordering': ['name'],
            },
        ),
    ]
