# Generated by Django 5.1.7 on 2025-04-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
