# Generated by Django 5.1.7 on 2025-03-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportscategory',
            name='friday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sportscategory',
            name='monday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sportscategory',
            name='thursday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sportscategory',
            name='tuesday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sportscategory',
            name='wednesday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
