# Generated by Django 5.1.7 on 2025-03-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_roles_alter_member_status'),
        ('sport', '0002_sportscategory_friday_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportscategory',
            options={'ordering': ['-start_year'], 'verbose_name_plural': 'Sports categories'},
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la performance')),
                ('description', models.TextField(verbose_name='Détails de la performance')),
                ('creation_date', models.DateField(verbose_name='Date de réalisation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='members.member')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200, verbose_name='Événement')),
                ('position', models.PositiveIntegerField(verbose_name='Position obtenue')),
                ('date_event', models.DateField(verbose_name="Date de l'événement")),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='members.member')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['-date_event'],
            },
        ),
    ]
