# Generated by Django 5.1.6 on 2025-02-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
