# Generated by Django 5.1.7 on 2025-04-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_image_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('square', 'Square')], default='landscape', max_length=10),
        ),
    ]
