# Generated by Django 5.1.7 on 2025-05-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
