# Generated by Django 5.1.7 on 2025-05-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
